title: xcw studyspace
author: xcw
email: curryjam_cg@sjtu.edu.cn
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: false # set to true to show excerpts on the homepage
# url: https://currybur.github.io/
# baseurl: /
# remote_theme: thelehhman/texture
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: ç‹å­è¯šçš„åšå®¢
  tagline: ğŸğŸ“šğŸ’»
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false
  navigation:
    - title: home
      url: "/"
    - title: My Work
      url: "/my-work"
    - title: Resume
      url: "/resume"
  # disqus_shortname: games

  # generate social links in footer
  social_links:
    twitter: ChengG212
    github:  currybur
    # linkedIn: in/thelehhman
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed